---
- hosts: "{{hosts}}"
  become: yes
  tasks:
   - name: "Reboot if required"
     shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
     async: 1
     poll: 0
     ignore_errors: true

   - name: "Wait for reboot"
     local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=10 state=started
     become: false
