---
- hosts: "{{hosts}}"
  become: yes
  tasks:
    - name: reboot nodes
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for server to come back
      local_action: wait_for
      args:
        host: "{{ hosts }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
     - name: check the uptime
       shell: echo $uptime


