---
- hosts: "{{hosts}}"
  become: true
  tasks: 
    - name: changing hostname in server
      shell: hostnamectl set-hostname "{{server_name}}" 
      shell: "hostname"
      register: pl_name
    - debug:
        msg: "name : {{pl_name.stdout}}"

    - name: install ip package
      yum: name=net-tools state=present update_cache=yes
  
#    - name: create jenkins user
#      shell:   
#      
#    - name: Generate SSH keys
#      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
#      args:
#        creates: /root/.ssh/id_rsa
#    
#    - name: copy the key
#      shell 
